# If you dont have both containers already created the app wont connect due to application starting before db accept connections
services:
  postgres:
    image: "postgres:latest"
    container_name: go_learn_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d # Execute initialization scripts
    networks:
      - go-learn-network

  app:
    build: .
    container_name: go_learn_app
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - go-learn-network
    ports:
      - "8080:8080"
    command: go run cmd/server/main.go

volumes:
  postgres_data:

networks:
  go-learn-network:
    driver: bridge
